### ISSUE TITLE
SparkContext: Error initializing SparkContext while trying to run ml.Flight 

### ISSUE THREAD

**Issue by tharindur-dev** [caroljmcdonald/spark-ml-flightdelay#1]
Hi, 
When I tried to run ml.Flight in the sandbox I get the following error. I'm new to Scala and any help is much appreciated. Thanks in advance.

```
[user01@maprdemo ~]$ spark-submit --class ml.Flight --master local[2] spark-ml-flightdelay-1.0.jar
Warning: Unable to determine $DRILL_HOME
18/12/19 05:02:09 WARN Utils: Your hostname, maprdemo.local resolves to a loopback address: 127.0.0.1; using 10.0.3.1 instead (on interface enp0s3)
18/12/19 05:02:09 WARN Utils: Set SPARK_LOCAL_IP if you need to bind to another address
18/12/19 05:02:20 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
18/12/19 05:02:27 ERROR SparkContext: Error initializing SparkContext.
java.io.IOException: Could not create FileClient
	at com.mapr.fs.MapRFileSystem.lookupClient(MapRFileSystem.java:656)
	at com.mapr.fs.MapRFileSystem.lookupClient(MapRFileSystem.java:709)
	at com.mapr.fs.MapRFileSystem.getMapRFileStatus(MapRFileSystem.java:1419)
	at com.mapr.fs.MapRFileSystem.getFileStatus(MapRFileSystem.java:1093)
	at org.apache.spark.scheduler.EventLoggingListener.start(EventLoggingListener.scala:100)
	at org.apache.spark.SparkContext.<init>(SparkContext.scala:522)
	at org.apache.spark.SparkContext$.getOrCreate(SparkContext.scala:2493)
	at org.apache.spark.sql.SparkSession$Builder$$anonfun$7.apply(SparkSession.scala:933)
	at org.apache.spark.sql.SparkSession$Builder$$anonfun$7.apply(SparkSession.scala:924)
	at scala.Option.getOrElse(Option.scala:121)
	at org.apache.spark.sql.SparkSession$Builder.getOrCreate(SparkSession.scala:924)
	at ml.Flight$.main(Flight.scala:37)
	at ml.Flight.main(Flight.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.spark.deploy.JavaMainApplication.start(SparkApplication.scala:52)
	at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:899)
	at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:198)
	at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:228)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:137)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
Caused by: java.io.IOException: Could not create FileClient
	at com.mapr.fs.MapRClientImpl.<init>(MapRClientImpl.java:137)
	at com.mapr.fs.MapRFileSystem.lookupClient(MapRFileSystem.java:650)
	... 22 more
18/12/19 05:02:27 ERROR SparkSubmit: Could not create FileClient
java.io.IOException: Could not create FileClient
	at com.mapr.fs.MapRFileSystem.lookupClient(MapRFileSystem.java:656)
	at com.mapr.fs.MapRFileSystem.lookupClient(MapRFileSystem.java:709)
	at com.mapr.fs.MapRFileSystem.getMapRFileStatus(MapRFileSystem.java:1419)
	at com.mapr.fs.MapRFileSystem.getFileStatus(MapRFileSystem.java:1093)
	at org.apache.spark.scheduler.EventLoggingListener.start(EventLoggingListener.scala:100)
	at org.apache.spark.SparkContext.<init>(SparkContext.scala:522)
	at org.apache.spark.SparkContext$.getOrCreate(SparkContext.scala:2493)
	at org.apache.spark.sql.SparkSession$Builder$$anonfun$7.apply(SparkSession.scala:933)
	at org.apache.spark.sql.SparkSession$Builder$$anonfun$7.apply(SparkSession.scala:924)
	at scala.Option.getOrElse(Option.scala:121)
	at org.apache.spark.sql.SparkSession$Builder.getOrCreate(SparkSession.scala:924)
	at ml.Flight$.main(Flight.scala:37)
	at ml.Flight.main(Flight.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.spark.deploy.JavaMainApplication.start(SparkApplication.scala:52)
	at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:899)
	at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:198)
	at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:228)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:137)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
Caused by: java.io.IOException: Could not create FileClient
	at com.mapr.fs.MapRClientImpl.<init>(MapRClientImpl.java:137)
	at com.mapr.fs.MapRFileSystem.lookupClient(MapRFileSystem.java:650)
	... 22 more

```

**Comment by caroljmcdonald** [comment]
try  following the directions on the readme exactly. Did you log in as user
mapr ?  The problem is Could not create FileClient
try hadoop fs -ls /
